### ISSUE TITLE
Apk size and/or methods count difference after redex pass?

### ISSUE THREAD

**Issue by meoyawn** [timmutton/redex-plugin#2]
Do you want to add any stats to redex task output?
Maybe the difference in size it made?

**Comment by timmutton** [comment]
Sorry for not replying sooner, my email filter must have caught this. Difference in size shouldnt be too hard (depending on platform), different in method count might be trickier (depending on what info redex itself gives us)

**Comment by ghost** [comment]
I have some numbers.
My dex files contains 66k methods.
After using Proguard with optimizations (5 passes) count of methods down to 55k.
After applying Redex on top of that apk (55k) I got a new apk with 52k of methods.

So after two step optimizations I reduced dex method count significantly. Please note that facebook recommends to use Redex on top of ProGuard as I did.

(yeah, app was running smooth, but I can't compare the diff in performance between two versions).

**Comment by timmutton** [comment]
@nethergrim Sorry this took so long, but the plugin now displays how many methods and fields have been removed
