### ISSUE TITLE
redex-break error when execution

### ISSUE THREAD

**Issue by linsea** [timmutton/redex-plugin#3]
gradle run debug log : 

14:55:47.197 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:assembleDebug (Thread[main,5,main]) completed. Took 0.001 secs.
14:55:47.197 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:redexDebug (Thread[main,5,main]) started.
14:55:47.197 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:redexDebug
14:55:47.197 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':app:redexDebug'
14:55:47.197 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':app:redexDebug' is up-to-date
14:55:47.197 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':app:redexDebug' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
14:55:47.198 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':app:redexDebug'.
14:55:47.247 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'redex-break''. Working directory: /home/andy/AndroidStudioProjects/ComApp/app Command: redex-break -c /home/andy/AndroidStudioProjects/ComApp/app/build/redex.config --sign --keystore /home/andy/.android/debug.keystore --keyalias AndroidDebugKey --keypass android /home/andy/AndroidStudioProjects/ComApp/app/build/outputs/apk/app-debug.apk -o /home/andy/AndroidStudioProjects/ComApp/app/build/outputs/apk/app-debug-redex.apk
14:55:47.247 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Environment for process 'command 'redex-break'': {PATH=/home/andy/github/redex/usr/lib/jvm/jdk1.8.0_92/bin:/home/andy/Android/Sdk/platform-tools:/home/andy/Android/Sdk/platforms:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games, ......................................
14:55:47.248 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
14:55:47.249 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'redex-break'.
14:55:47.251 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
14:55:47.252 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'redex-break'' finished with exit value -1 (state: FAILED)
14:55:47.253 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:redexDebug'
14:55:47.254 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:redexDebug FAILED
14:55:47.254 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:redexDebug (Thread[main,5,main]) completed. Took 0.057 secs.
14:55:47.255 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 0.397 secs, idle: 0.01 secs
14:55:47.263 [ERROR] [org.gradle.BuildExceptionReporter] 
14:55:47.264 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:55:47.264 [ERROR] [org.gradle.BuildExceptionReporter] 
14:55:47.264 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
14:55:47.264 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:redexDebug'.
14:55:47.264 [ERROR] [org.gradle.BuildExceptionReporter] > A problem occurred starting Redex. Ensure you have installed Redex using the instructions at https://github.com/facebook/redex
14:55:47.264 [ERROR] [org.gradle.BuildExceptionReporter] 
14:55:47.264 [ERROR] [org.gradle.BuildExceptionReporter] \* Try:
14:55:47.265 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
14:55:47.265 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:55:47.265 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
14:55:47.265 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:55:47.266 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 4.491 secs

I have put redex executable to the PATH,(as you can see in the log), why exec command is 'redex-break' instead of 'redex' ?

**Comment by deepti1408** [comment]
hi @linsea @timmutton : yes i am struggling to get this working. getting the same error, even though i have redex  installed in my machine. Have added this in my PATH variable as well . Still no luck. 

Have you found a solution yet?

Thanks!

**Comment by ghost** [comment]
Same error here.

**Comment by timmutton** [comment]
@deepti1408 @nethergrim version 1.1.0 should fix this error

**Comment by timmutton** [comment]
@linsea forgot to tag you as well
