### ISSUE TITLE
How to know if plugin runs correctly

### ISSUE THREAD

**Issue by andhie** [timmutton/redex-plugin#4]
In the Gradle Console log, there are no traces of the Redex plugin actually run. So i'm not too such if it actually done anything. 
Is there a way to know for sure redex has been applied?

**Comment by timmutton** [comment]
@andhie the plugin now shows you how many methods and fields have been removed

**Comment by charpeni** [comment]
@timmutton the README is not up-to-date. Even with 1.2.0, it doesn't show anything.
